version: '2'

services:
  web:
    build: .
    volumes:
      - ./cache:/var/www/letter-avatars/cache
    environment:
      - TEMP_FILE_PATH=/var/www/letter-avatars/cache
    expose:
      - "8080"
  nginx:
    build: ./nginx
    volumes:
      - ./cache:/var/www/letter-avatars/cache
    links:
      - web
    ports:
      - "82:80"
